services:
  flask:
    build: ./flask
    volumes:
      - ./flask:/code
    ports:
      - "${FLASK_PORT}:5000"
    environment:
      - APP_ENV
      - POSTGRES_DB
      - POSTGRES_HOST
      - POSTGRES_PASSWORD
      - POSTGRES_ROOT_PASSWORD
      - POSTGRES_USER
      - TEST_DB_NAME
      - FLASK_APP_DEBUG=false
    # entrypoint: ["gunicorn", "api.app:create_app()", "-w", "2", "-b", "0.0.0.0:5000"]
  next:
    image: node:22-slim
    working_dir: /app/cycle-network-toy
    entrypoint: yarn dev
    environment:
      - NEXT_PUBLIC_API_ENDPOINT_BROWSER=${API_ENDPOINT_BROWSER}
      - NEXT_PUBLIC_API_ENDPOINT_INTERNAL=${API_ENDPOINT_INTERNAL}
    volumes:
      - "./next:/app"
    ports:
      - "${NEXT_PORT}:3000"
    user: "1000"
  postgres:
    image: postgis/postgis:15-3.3
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB
      - POSTGRES_HOST_AUTH_METHOD=password
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_ROOT_PASSWORD

volumes:
  db-data:

