"""initial

Revision ID: 1cbb7a102030
Revises:
Create Date: 2024-02-06 15:07:04.294885

"""

from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1cbb7a102030"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "budgets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_budgets_id"), "budgets", ["id"], unique=False)
    op.create_table(
        "improvement_features",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("GEO_ID", sa.Integer(), nullable=True),
        sa.Column("LFN_ID", sa.Integer(), nullable=True),
        sa.Column("LF_NAME", sa.String(), nullable=True),
        sa.Column("ADDRESS_L", sa.String(), nullable=True),
        sa.Column("ADDRESS_R", sa.String(), nullable=True),
        sa.Column("OE_FLAG_L", sa.String(), nullable=True),
        sa.Column("OE_FLAG_R", sa.String(), nullable=True),
        sa.Column("LONUML", sa.Integer(), nullable=True),
        sa.Column("HINUML", sa.Integer(), nullable=True),
        sa.Column("LONUMR", sa.Integer(), nullable=True),
        sa.Column("HINUMR", sa.Integer(), nullable=True),
        sa.Column("FNODE", sa.Integer(), nullable=True),
        sa.Column("TNODE", sa.Integer(), nullable=True),
        sa.Column("ONE_WAY_DI", sa.Integer(), nullable=True),
        sa.Column("DIR_CODE_D", sa.String(), nullable=True),
        sa.Column("FCODE", sa.Integer(), nullable=True),
        sa.Column("FCODE_DESC", sa.String(), nullable=True),
        sa.Column("JURIS_CODE", sa.String(), nullable=True),
        sa.Column("OBJECTID", sa.Float(), nullable=True),
        sa.Column("CP_TYPE", sa.String(), nullable=True),
        sa.Column("SPEED", sa.Integer(), nullable=True),
        sa.Column("NBRLANES_2", sa.Integer(), nullable=True),
        sa.Column("length_in_", sa.Float(), nullable=True),
        sa.Column("Shape_Leng", sa.Float(), nullable=True),
        sa.Column("U500_20", sa.String(), nullable=True),
        sa.Column(
            "geometry",
            geoalchemy2.types.Geometry(
                geometry_type="LINESTRING", from_text="ST_GeomFromEWKT", name="geometry"
            ),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("GEO_ID"),
    )
    op.create_index(
        op.f("ix_improvement_features_id"), "improvement_features", ["id"], unique=False
    )
    op.create_table(
        "budgets_improvement_features",
        sa.Column("budget_id", sa.Integer(), nullable=False),
        sa.Column("improvement_feature_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["budget_id"],
            ["budgets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["improvement_feature_id"],
            ["improvement_features.id"],
        ),
        sa.PrimaryKeyConstraint("budget_id", "improvement_feature_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("budgets_improvement_features")
    op.drop_index(op.f("ix_improvement_features_id"), table_name="improvement_features")
    op.drop_table("improvement_features")
    op.drop_index(op.f("ix_budgets_id"), table_name="budgets")
    op.drop_table("budgets")
    # ### end Alembic commands ###
