"""initial

Revision ID: 2c8f70e038aa
Revises:
Create Date: 2024-02-08 21:21:26.503621

"""

from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2c8f70e038aa"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "budgets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_budgets_id"), "budgets", ["id"], unique=False)
    op.create_table(
        "dissemination_areas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("DAUID", sa.Integer(), nullable=False),
        sa.Column("PRUID", sa.Integer(), nullable=True),
        sa.Column("PRNAME", sa.String(), nullable=True),
        sa.Column("CDUID", sa.Integer(), nullable=True),
        sa.Column("CDNAME", sa.String(), nullable=True),
        sa.Column("CDTYPE", sa.String(), nullable=True),
        sa.Column("CCSUID", sa.Integer(), nullable=True),
        sa.Column("CCSNAME", sa.String(), nullable=True),
        sa.Column("CSDUID", sa.Integer(), nullable=True),
        sa.Column("CSDNAME", sa.String(), nullable=True),
        sa.Column("CSDTYPE", sa.String(), nullable=True),
        sa.Column("ERUID", sa.Integer(), nullable=True),
        sa.Column("ERNAME", sa.String(), nullable=True),
        sa.Column("SACCODE", sa.Integer(), nullable=True),
        sa.Column("SACTYPE", sa.String(), nullable=True),
        sa.Column("CMAUID", sa.Integer(), nullable=True),
        sa.Column("CMAPUID", sa.Integer(), nullable=True),
        sa.Column("CMANAME", sa.String(), nullable=True),
        sa.Column("CMATYPE", sa.String(), nullable=True),
        sa.Column("CTUID", sa.Float(), nullable=True),
        sa.Column("CTNAME", sa.Float(), nullable=True),
        sa.Column("ADAUID", sa.Integer(), nullable=True),
        sa.Column("DAUID_int", sa.Integer(), nullable=True),
        sa.Column("Shape_Leng", sa.Float(), nullable=True),
        sa.Column("Shape_Area", sa.Float(), nullable=True),
        sa.Column(
            "geometry",
            geoalchemy2.types.Geometry(
                geometry_type="MULTIPOLYGON",
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("DAUID"),
    )
    op.create_index(
        op.f("ix_dissemination_areas_id"), "dissemination_areas", ["id"], unique=False
    )
    op.create_table(
        "improvement_features",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("GEO_ID", sa.Integer(), nullable=True),
        sa.Column("LFN_ID", sa.Integer(), nullable=True),
        sa.Column("LF_NAME", sa.String(), nullable=True),
        sa.Column("ADDRESS_L", sa.String(), nullable=True),
        sa.Column("ADDRESS_R", sa.String(), nullable=True),
        sa.Column("OE_FLAG_L", sa.String(), nullable=True),
        sa.Column("OE_FLAG_R", sa.String(), nullable=True),
        sa.Column("LONUML", sa.Integer(), nullable=True),
        sa.Column("HINUML", sa.Integer(), nullable=True),
        sa.Column("LONUMR", sa.Integer(), nullable=True),
        sa.Column("HINUMR", sa.Integer(), nullable=True),
        sa.Column("FNODE", sa.Integer(), nullable=True),
        sa.Column("TNODE", sa.Integer(), nullable=True),
        sa.Column("ONE_WAY_DI", sa.Integer(), nullable=True),
        sa.Column("DIR_CODE_D", sa.String(), nullable=True),
        sa.Column("FCODE", sa.Integer(), nullable=True),
        sa.Column("FCODE_DESC", sa.String(), nullable=True),
        sa.Column("JURIS_CODE", sa.String(), nullable=True),
        sa.Column("OBJECTID", sa.Float(), nullable=True),
        sa.Column("CP_TYPE", sa.String(), nullable=True),
        sa.Column("SPEED", sa.Integer(), nullable=True),
        sa.Column("NBRLANES_2", sa.Integer(), nullable=True),
        sa.Column("length_in_", sa.Float(), nullable=True),
        sa.Column("Shape_Leng", sa.Float(), nullable=True),
        sa.Column("U500_20", sa.String(), nullable=True),
        sa.Column(
            "geometry",
            geoalchemy2.types.Geometry(
                geometry_type="LINESTRING",
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("GEO_ID"),
    )

    op.create_index(
        op.f("ix_improvement_features_id"), "improvement_features", ["id"], unique=False
    )
    op.create_table(
        "metrics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_metrics_id"), "metrics", ["id"], unique=False)
    op.create_table(
        "budgets_improvement_features",
        sa.Column("budget_id", sa.Integer(), nullable=False),
        sa.Column("improvement_feature_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["budget_id"],
            ["budgets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["improvement_feature_id"],
            ["improvement_features.id"],
        ),
        sa.PrimaryKeyConstraint("budget_id", "improvement_feature_id"),
    )
    op.create_table(
        "feature_scores",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("metric_id", sa.Integer(), nullable=False),
        sa.Column("improvement_feature_id", sa.Integer(), nullable=False),
        sa.Column("dissemination_area_id", sa.Integer(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dissemination_area_id"],
            ["dissemination_areas.id"],
        ),
        sa.ForeignKeyConstraint(
            ["improvement_feature_id"],
            ["improvement_features.id"],
        ),
        sa.ForeignKeyConstraint(
            ["metric_id"],
            ["metrics.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "dissemination_area_id", "metric_id", "improvement_feature_id"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table("feature_scores")
    op.drop_table("budgets_improvement_features")
    op.drop_index(op.f("ix_metrics_id"), table_name="metrics")
    op.drop_table("metrics")
    op.drop_index(op.f("ix_improvement_features_id"), table_name="improvement_features")

    op.drop_table("improvement_features")
    op.drop_index(op.f("ix_dissemination_areas_id"), table_name="dissemination_areas")

    op.drop_table("dissemination_areas")
    op.drop_index(op.f("ix_budgets_id"), table_name="budgets")
    op.drop_table("budgets")
    # ### end Alembic commands ###
