"""add intersections

Revision ID: 6c8afbf21a46
Revises: fe6e20733b38
Create Date: 2024-12-12 15:29:03.112319

"""

from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6c8afbf21a46"
down_revision: Union[str, None] = "fe6e20733b38"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "intersections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("INTERSECTION_ID", sa.Integer(), nullable=False),
        sa.Column("ELEVATION_ID", sa.Integer(), nullable=True),
        sa.Column("INTERSECTION_DESC", sa.String(), nullable=True),
        sa.Column("CLASSIFICATION", sa.String(), nullable=True),
        sa.Column("CLASSIFICATION_DESC", sa.String(), nullable=True),
        sa.Column("OBJECTID", sa.Integer(), nullable=True),
        sa.Column(
            "geometry",
            geoalchemy2.types.Geometry(
                geometry_type="MULTIPOINT",
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_intersections_id"), "intersections", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_intersections_id"), table_name="intersections")
    op.drop_table("intersections")
    # ### end Alembic commands ###
