"""make metrics nullable

Revision ID: 844a2c87d193
Revises: cedefc9b87ad
Create Date: 2024-03-22 13:18:48.110233

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "844a2c87d193"
down_revision: Union[str, None] = "cedefc9b87ad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "budget_scores", "budget_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "budget_scores", "budget_id", existing_type=sa.INTEGER(), nullable=False
    )

    # ### end Alembic commands ###
