"""add existing lanes

Revision ID: cedefc9b87ad
Revises: 195c2ec60033
Create Date: 2024-03-08 15:00:23.077352

"""

from typing import Sequence, Union

import geoalchemy2
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cedefc9b87ad"
down_revision: Union[str, None] = "195c2ec60033"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "existing_lanes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("_id", sa.Integer(), nullable=True),
        sa.Column("OBJECTID", sa.Integer(), nullable=True),
        sa.Column("SEGMENT_ID", sa.Integer(), nullable=True),
        sa.Column("INSTALLED", sa.Integer(), nullable=True),
        sa.Column("UPGRADED", sa.Integer(), nullable=True),
        sa.Column("PRE_AMALGAMATION", sa.String(), nullable=True),
        sa.Column("STREET_NAME", sa.String(), nullable=True),
        sa.Column("FROM_STREET", sa.String(), nullable=True),
        sa.Column("TO_STREET", sa.String(), nullable=True),
        sa.Column("ROADCLASS", sa.String(), nullable=True),
        sa.Column("CNPCLASS", sa.String(), nullable=True),
        sa.Column("SURFACE", sa.String(), nullable=True),
        sa.Column("OWNER", sa.String(), nullable=True),
        sa.Column("DIR_LOWORDER", sa.String(), nullable=True),
        sa.Column("INFRA_LOWORDER", sa.String(), nullable=True),
        sa.Column("SEPA_LOWORDER", sa.String(), nullable=True),
        sa.Column("SEPB_LOWORDER", sa.String(), nullable=True),
        sa.Column("ORIG_LOWORDER_INFRA", sa.String(), nullable=True),
        sa.Column("DIR_HIGHORDER", sa.String(), nullable=True),
        sa.Column("INFRA_HIGHORDER", sa.String(), nullable=True),
        sa.Column("SEPA_HIGHORDER", sa.String(), nullable=True),
        sa.Column("SEPB_HIGHORDER", sa.String(), nullable=True),
        sa.Column("ORIG_HIGHORDER", sa.String(), nullable=True),
        sa.Column("BYLAWED", sa.String(), nullable=True),
        sa.Column("EDITOR", sa.String(), nullable=True),
        sa.Column("LAST_EDIT_DATE", sa.String(), nullable=True),
        sa.Column("UPGRADE_DESCRIPTION", sa.String(), nullable=True),
        sa.Column("CONVERTED", sa.String(), nullable=True),
        sa.Column(
            "geometry",
            geoalchemy2.types.Geometry(
                geometry_type="MultiLineString",
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(
        op.f("ix_existing_lanes_id"), "existing_lanes", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_existing_lanes_id"), table_name="existing_lanes")
    op.drop_table("existing_lanes")
    # ### end Alembic commands ###
